name: DAG Workflow Practice

on:
  "workflow_dispatch":

jobs:
  job-1:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello world!!!!"

  job-2:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello world from job 2"

  job-3:
    runs-on: ubuntu-24.04
    needs:
      - job-1
      - job-2
    steps:
      - run: echo "Hello world from job 2"

  job-4:
    runs-on: ubuntu-24.04
    needs:
      - job-2
      - job-3
    steps:
      - run: echo "...to form a directed acyclic graph (DAG)"
  
